// This file is @generated by prost-build.
pub mod build {
    pub mod bazel {
        pub mod remote {
            pub mod asset {
                pub mod v1 {
                    include!("build.bazel.remote.asset.v1.rs");
                }
            }
            pub mod execution {
                pub mod v2 {
                    include!("build.bazel.remote.execution.v2.rs");
                }
            }
        }
        pub mod semver {
            include!("build.bazel.semver.rs");
        }
    }
}
pub mod google {
    pub mod api {
        include!("google.api.rs");
    }
    pub mod longrunning {
        include!("google.longrunning.rs");
    }
    pub mod rpc {
        include!("google.rpc.rs");
    }
}
